services:
  postgres:
    container_name: simple_bank_dev_db
    image: postgres:12-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DEV_DB_USER}
      - POSTGRES_PASSWORD=${DEV_DB_PASSWORD}
      - POSTGRES_DB=${DEV_DB_NAME}
    ports:
      - "${DEV_DB_HOST_PORT}:${DEV_DB_CONTAINER_PORT}" # Host: 6433, Docker Container: 5433
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DEV_DB_USER} -p ${DEV_DB_CONTAINER_PORT}",
        ]
      interval: 5s
      timeout: 5s
      retries: ${DEV_DB_MAX_RETRIES}
    command: -p ${DEV_DB_CONTAINER_PORT} # Set PostgreSQL port
    networks:
      - bank-network

  redis:
    container_name: simple_bank_dev_redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "${DEV_REDIS_HOST_PORT:-6379}:6379"
    volumes:
      - redis-dev-data:/data
    command: redis-server --appendonly yes --requirepass ${DEV_REDIS_PASSWORD:-redispass}
    healthcheck:
      test:
        ["CMD", "redis-cli", "-a", "${DEV_REDIS_PASSWORD:-redispass}", "ping"]
      interval: 5s
      timeout: 5s
      retries: ${DEV_DB_MAX_RETRIES}
    networks:
      - bank-network

  api:
    container_name: simple_bank_dev_api
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    restart: on-failure:5

    env_file:
      - ./.env
    ports:
      - "${DEV_API_HOST_PORT}:${DEV_API_CONTAINER_PORT}" # http://localhost:8081
    volumes:
      - ../..:/app
    environment:
      # Database settings
      - DB_SOURCE=${DEV_DB_SOURCE}
      - DB_MAX_CONNS=${DEV_DB_MAX_CONNS}
      - DB_MIN_CONNS=${DEV_DB_MIN_CONNS}
      - DB_CONN_LIFETIME=${DEV_DB_CONN_LIFETIME}
      - DB_CONN_IDLE_TIME=${DEV_DB_CONN_IDLE_TIME}
      - DB_MAX_RETRIES=${DEV_DB_MAX_RETRIES}
      # Redis settings
      - REDIS_HOST=${DEV_REDIS_HOST:-redis}
      - REDIS_PORT=${DEV_REDIS_PORT:-6379}
      - REDIS_PASSWORD=${DEV_DEV_REDIS_PASSWORD}
      - REDIS_DB=${DEV_REDIS_DB:-0}
      - REDIS_POOL_SIZE=${DEV_REDIS_POOL_SIZE:-10}
      - REDIS_MIN_IDLE_CONNS=${DEV_REDIS_MIN_IDLE_CONNS:-3}
      - REDIS_MAX_CONN_LIFETIME=${DEV_REDIS_MAX_CONN_LIFETIME:-30m}
      - REDIS_IDLE_TIMEOUT=${DEV_REDIS_IDLE_TIMEOUT:-5m}
      - REDIS_DIAL_TIMEOUT=${DEV_REDIS_DIAL_TIMEOUT:-5s}
      - REDIS_READ_TIMEOUT=${DEV_REDIS_READ_TIMEOUT:-3s}
      - REDIS_WRITE_TIMEOUT=${DEV_REDIS_WRITE_TIMEOUT:-3s}
      # API settings
      - GIN_MODE=debug
      - PORT=${DEV_API_CONTAINER_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    command: air
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge

volumes:
  postgres-dev-data:
    name: simple_bank_dev_data
  redis-dev-data:
    name: simple_bank_dev_redis_data