// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

type Account struct {
	AccountID      int32          `json:"account_id"`
	UserID         int32          `json:"user_id"`
	AccountNumber  string         `json:"account_number"`
	AccountType    string         `json:"account_type"`
	Balance        pgtype.Numeric `json:"balance"`
	CurrencyCode   string         `json:"currency_code"`
	InterestRate   pgtype.Numeric `json:"interest_rate"`
	OverdraftLimit pgtype.Numeric `json:"overdraft_limit"`
	IsActive       bool           `json:"is_active"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type AccountCurrency struct {
	CurrencyCode  string         `json:"currency_code"`
	CurrencyName  string         `json:"currency_name"`
	Symbol        sql.NullString `json:"symbol"`
	IsActive      bool           `json:"is_active"`
	ExchangeRate  pgtype.Numeric `json:"exchange_rate"`
	LastUpdatedAt sql.NullTime   `json:"last_updated_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type AccountType struct {
	AccountType string    `json:"account_type"`
	Description string    `json:"description"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type AuditTrail struct {
	AuditID   int32          `json:"audit_id"`
	TableName string         `json:"table_name"`
	RecordID  int32          `json:"record_id"`
	Action    string         `json:"action"`
	OldValues pgtype.JSONB   `json:"old_values"`
	NewValues pgtype.JSONB   `json:"new_values"`
	UserID    sql.NullInt32  `json:"user_id"`
	IpAddress sql.NullString `json:"ip_address"`
	CreatedAt time.Time      `json:"created_at"`
}

type Transaction struct {
	TransactionID   int32          `json:"transaction_id"`
	FromAccountID   sql.NullInt32  `json:"from_account_id"`
	ToAccountID     sql.NullInt32  `json:"to_account_id"`
	TypeCode        string         `json:"type_code"`
	Amount          pgtype.Numeric `json:"amount"`
	CurrencyCode    string         `json:"currency_code"`
	ExchangeRate    pgtype.Numeric `json:"exchange_rate"`
	StatusCode      string         `json:"status_code"`
	Description     sql.NullString `json:"description"`
	ReferenceNumber sql.NullString `json:"reference_number"`
	TransactionDate time.Time      `json:"transaction_date"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type TransactionStatus struct {
	StatusCode  string    `json:"status_code"`
	Description string    `json:"description"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type TransactionType struct {
	TypeCode    string    `json:"type_code"`
	Description string    `json:"description"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type User struct {
	UserID       int32          `json:"user_id"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Email        sql.NullString `json:"email"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	IsActive     bool           `json:"is_active"`
	LastLogin    time.Time      `json:"last_login"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
