// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAccountType(ctx context.Context, arg CreateAccountTypeParams) (AccountType, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransactionStatus(ctx context.Context, arg CreateTransactionStatusParams) (TransactionStatus, error)
	CreateTransactionType(ctx context.Context, arg CreateTransactionTypeParams) (TransactionType, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, accountID int32) error
	DeleteAccountType(ctx context.Context, accountType string) error
	DeleteCurrency(ctx context.Context, currencyCode string) error
	DeleteTransactionStatus(ctx context.Context, statusCode string) error
	DeleteTransactionType(ctx context.Context, typeCode string) error
	DeleteUser(ctx context.Context, userID int32) error
	GetAccount(ctx context.Context, accountID int32) (Account, error)
	GetAccountForUpdate(ctx context.Context, accountID int32) (Account, error)
	GetActiveTransactionStatus(ctx context.Context, dollar_1 []string) ([]TransactionStatus, error)
	GetCurrency(ctx context.Context, currencyCode string) (AccountCurrency, error)
	GetTransaction(ctx context.Context, transactionID int32) (Transaction, error)
	GetTransactionStatus(ctx context.Context, statusCode string) (TransactionStatus, error)
	GetTransactionType(ctx context.Context, typeCode string) (TransactionType, error)
	GetTransactionsByDateRange(ctx context.Context, arg GetTransactionsByDateRangeParams) ([]Transaction, error)
	GetUser(ctx context.Context, userID int32) (User, error)
	HardDeleteAccount(ctx context.Context, accountID int32) error
	HardDeleteAccountType(ctx context.Context, accountType string) error
	HardDeleteCurrency(ctx context.Context, currencyCode string) error
	HardDeleteTransactionStatus(ctx context.Context, statusCode string) error
	HardDeleteTransactionType(ctx context.Context, typeCode string) error
	HardDeleteUser(ctx context.Context, userID int32) error
	ListAccountTypes(ctx context.Context) ([]AccountType, error)
	ListAccountsByUser(ctx context.Context, userID int32) ([]Account, error)
	ListCurrencies(ctx context.Context) ([]AccountCurrency, error)
	ListTransactionStatus(ctx context.Context) ([]TransactionStatus, error)
	ListTransactionTypes(ctx context.Context) ([]TransactionType, error)
	ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ModifyTransactionStatus(ctx context.Context, arg ModifyTransactionStatusParams) (TransactionStatus, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateAccountType(ctx context.Context, arg UpdateAccountTypeParams) (AccountType, error)
	UpdateExchangeRate(ctx context.Context, arg UpdateExchangeRateParams) (AccountCurrency, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error)
	UpdateTransactionType(ctx context.Context, arg UpdateTransactionTypeParams) (TransactionType, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
