# .github/workflows/go-test.yml
name: Go Test Pipeline

# Only manual trigger
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to run tests"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  run-tests:
    name: Run Unit and Integration Tests
    runs-on: ubuntu-latest

    services:
      test-db:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123321
          POSTGRES_DB: simple_bank_dev
        ports:
          - 6432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.5"

      - name: Create test env file
        run: |
          cat << EOF > .env.test
          TEST_DB_HOST=localhost
          TEST_DB_PORT=6432
          TEST_DB_USER=postgres
          TEST_DB_PASSWORD=123321
          TEST_DB_NAME=simple_bank_dev
          TEST_DB_SSLMODE=disable
          EOF

      - name: Install database migration tool
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/bin/migrate
          which migrate

      - name: Run database migrations
        run: make migrate-dev-up

      - name: Clean test cache
        run: make clean-test-cache

      - name: Run tests
        run: make test
